# Generated by Django 5.0 on 2024-11-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedbacks',
        ),
    ]
