# Generated by Django 5.1.3 on 2024-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_contact_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_choose',
        ),
        migrations.AddField(
            model_name='product',
            name='VAT',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
