# Generated by Django 5.1.3 on 2024-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_product_category_choose_product_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('order_creation_date', models.DateTimeField()),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='Order_product_Images')),
            ],
        ),
    ]
