# Generated by Django 5.1.3 on 2024-11-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_me',
            field=models.TextField(),
        ),
    ]
