# Generated by Django 5.0 on 2024-11-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sv_img',
            options={},
        ),
        migrations.AlterModelTable(
            name='sv_img',
            table=None,
        ),
    ]
