# Generated by Django 5.0 on 2024-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_product', '0002_alter_sv_img_options_alter_sv_img_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sv_img',
            name='img_name',
            field=models.ImageField(blank=True, upload_to='Media'),
        ),
    ]
