# Generated by Django 5.0 on 2024-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Password', models.CharField(max_length=200)),
            ],
        ),
    ]
