# Generated by Django 5.0 on 2024-11-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserLogin',
        ),
    ]
